### PR TITLE
Fix Go module name

### PR DESCRIPTION
**Pull request by dolmen**
Fix the Go module name: `lb-experts/golbd` -> `gitlab.cern.ch/lb-experts/golbd`

The replace line in go.mod is also removed as it becomes useless.

### CODE REVIEW

**Comment by dolmen** [comment]
@reguero Could you review this PR?

**Comment by dolmen** [comment]
@reguero Could you review this PR?

**Comment by psaiz** [comment]
@dolmen , thanks a lot for this pull request. We have been discussing it internally in the team, and the current consensus is not to merge it. We are concerned that it would make the development trickier if we don't keep the link to override the code available in the repo with the one locally on the development nodes.

**Comment by dolmen** [comment]
@psaiz I don't understand your concerns. The project is in "go module" mode, so the project can be checkout anywhere. What counts is the module root given in the `module` line of `go.mod`.

@sbinet Could you review this?

**Comment by sbinet** [comment]
I don't want to stamp on anyone's toe.
but I'd tend to agree with having a more streamlined dev' environment (and limit the amount of `go replace` tricks).
I don't see what is the concern evocated above, _wrt_ development nodes.
could you (@psaiz) explain?

**Comment by dolmen** [comment]
Rebased on top of #20.

(Go Hack is done, but my contributions aren't)

**Comment by dolmen** [comment]
Thanks for merging @reguero ! 🎉

**Pull request merged**
