### PR TITLE
golbd: use bufio.Scanner to extract lines

### PR DESCRIPTION
**Pull request by sbinet**
This CL applies `gofmt -s -w` and `goimport` on the top-level Go files as well as some Go-related good practices.

Also, it introduces the use of `bufio.Scanner` to extract lines from an `io.Reader`.

### CODE REVIEW

**Comment by psaiz** [comment]
Hi Sebastien,

Thanks a lot for the pull request. The changes mentioned here make quite a lot of sense. The issue that we have is that, at the moment, the version of golbd that we have on this repo is slightly behind what we have in our internal repo. 

We've been working on the internal repo, adding also the 'go fmt' of the source code. Once we are ready with that, we will push those changes also here. At that point,  would you mind rebasing your branch, so that we can compare the differences again?

Thanks again, 
pablo

**Comment by sbinet** [comment]
SGTM.

(alternatively, I could send a MR directly against gitlab.cern...)

**Comment by psaiz** [comment]
Hi, 
Thanks for the quick reply. The MR against gitlab.cern.ch would be even better! Then, it would go through our internal building process,
Thanks again, 
pablo

**Comment by reguero** [comment]
Dear Sebastien,

I applied the latest changes from gitlab.cern.ch and merged your request on top of them.
I will be pushing this back to gitlab.cern.ch shortly.
Many thanks for your contribution.

                          Best regards  ...Ignacio...

**Pull request merged**
