### PR TITLE
[Go Hack] Tests Improvements

### PR DESCRIPTION
**Pull request by leon-sleepinglion**
This is a submission for [Go Hack's CERN Collaboration Track](https://gohack.devpost.com/details/cerntrack#h_8646478707841645659720080).

I noticed the `TestGetStateDNS` test case is always failing on my machine as it cannot get the A and AAAA records for `aiermis.cern.ch`,  I suspect it is the same case for everyone else outside of CERN's network.

```
--- FAIL: TestGetStateDNS (0.37s)
    get_state_dns_test.go:45: 
        got ips
        []string type and value []
        expected
        []string type and value [188.184.104.111 2001:1458:d00:2d::100:58]
```

In order to facilitate contributions from individuals outside of CERN, perhaps we should update the test case and allow it to run reliably from anywhere.

Hence, I have added a very minimal DNS server adapted from [Andreas Wålm's Gist](https://gist.github.com/walm/0d67b4fb2d5daf3edd4fad3e13b162cb) which can be used to test functions that will perform DNS queries and updates.

The main changes include:
- add functions to set up a simple local DNS server
- make TestGetStateDNS pass by using the local DNS server
- add test cases for RefreshDNS to improve test coverage
- allow users to specify the port of dnsmanager

@reguero Do you mind giving this PR a look? I am quite new to Go and I appreciate every feedback you can give!

### CODE REVIEW

**Comment by reguero** [comment]
Dear @leon-sleepinglion ,
Cool! This is a nice idea!
I just see failures in TestRefreshDNS I think because we miss the handling of requests with TSIG keys.
I also had to change the port to a much higher one such as 54421so my system lets  the server listen.

**Comment by leon-sleepinglion** [comment]
Thanks for pointing those issues out @reguero. 🐛 

I have made these changes since:
- updated the port numbers to use a higher number while avoiding the [commonly used ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)
- fixed issue with comparing IPs using `DeepEqual` by stringifying the IPs before comparing them
- added TSIG handling to the local DNS server, while doing that, I had to bump the version of the DNS  library we are using up a little for it to parse the query properly

Do you mind having a look at it again?

**Comment by reguero** [comment]
Hi @leon-sleepinglion 
Many thanks! What you've done looks very cool!

As matter of fact, we cannot use the latest version of  github.com/miekg/dns  because we need to support TSIG keys using HmacMD5 until the software supporting the DNS servers at CERN is updated and github.com/miekg/dns has dropped support for it in later versions.

**Comment by leon-sleepinglion** [comment]
@reguero That's true, thanks for the context! I noticed the package has deprecated `HmacMD5` in the more recent versions and we probably don't want to change the hash algorithm without knowing what the production server supports.

Therefore I decided to go with v1.0.0 which allows us to handle TSIG properly in the test server while retaining the use of `HmacMD5`.

**Pull request merged**
